### ISSUE TITLE
Layout 150 SIACC CAIXA - Código do cliente com zeros a direita

### ISSUE THREAD

**Issue by paulop** [nielsonrocha/bank-layout#1]
Bom dia Nielson, 

Descobri seu repo pesquisando sobre SIACC 150 caixa.

Posso perguntar se tem algum problema nos arquivos de retorno da caixa?

Ao enviar uma remessa. O código identificador do cliente é alfanumérico mas está retornando com zeros a direita.

Nós enviamos um campo de Alfanumérico e ele é completado com zeros a direita pelo sistema da caixa no arquivo de retorno.

Você está tendo esse mesmo problema?

Obrigado e bom trabalho.

**Comment by nielsonrocha** [comment]
Boa tarde, isso também está acontecendo nos meus clientes, sempre a caixa está retornando o valor com zeros a direita. Entrei em contato com a central deles mas ainda não obtive resposta sobre isso. A solução de contorno pra isso é setar um parâmetro dentro da sua aplicação pra "truncar" o código do cliente. No meus clientes estou usando um código com 10 posições, e quando faço a leitura só considero essas 10. Se tiver mais algum questionamento fique a vontade, se quiser contribuir também será bem vindo

**Comment by paulop** [comment]
Eu perguntei para saber se erá só comigo. Mas vejo que está geral.
A CAIXA demora muito para dar um feedback.
Eu já faço da forma como mencionou.
Obrigado pela resposta!
